# Generated by Django 4.0.5 on 2022-09-13 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Domain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=100, unique=True)),
                ('company_email', models.EmailField(max_length=100, unique=True)),
                ('company_phone', models.CharField(max_length=100)),
                ('password', models.BinaryField()),
                ('verified', models.BooleanField(default=False)),
                ('pas_reset', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('is_admin', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=True)),
                ('Workspace_profile_img', models.ImageField(default='blank-profile-picture.png', upload_to='workspcae_img')),
            ],
        ),
        migrations.CreateModel(
            name='invitation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=100)),
                ('invitation_link', models.CharField(max_length=250, unique=True)),
                ('workspacename', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('type', models.CharField(max_length=50)),
                ('location', models.TextField()),
                ('data', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=250, null=True)),
                ('role', models.CharField(default='Null', max_length=50)),
                ('email', models.CharField(max_length=225, unique=True)),
                ('password', models.BinaryField()),
                ('profile_img', models.ImageField(default='blank-profile-picture.png', upload_to='profile_img')),
                ('is_admin', models.BooleanField(default=False)),
                ('is_staff', models.BooleanField(default=True)),
                ('pas_reset', models.BooleanField(default=False)),
                ('domain', models.TextField()),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'api_user',
            },
        ),
        migrations.CreateModel(
            name='Worklog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=100)),
                ('date', models.DateField()),
                ('clockintime', models.TimeField(default='00:00:00.00')),
                ('clockouttime', models.TimeField(default='00:00:00.00')),
                ('workhour', models.TimeField(default='00:00:00.00')),
                ('workspace', models.CharField(max_length=100)),
            ],
        ),
    ]
