# Generated by Django 4.0.5 on 2022-09-14 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_delete_domain'),
    ]

    operations = [
        migrations.CreateModel(
            name='Domain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=100, unique=True)),
                ('company_email', models.EmailField(max_length=100, unique=True)),
                ('company_phone', models.CharField(max_length=100)),
                ('password', models.BinaryField()),
                ('verified', models.BooleanField(default=False)),
                ('pas_reset', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('is_admin', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=True)),
                ('Workspace_profile_img', models.ImageField(default='blank-profile-picture.png', upload_to='workspcae_img')),
            ],
        ),
    ]
