# Generated by Django 4.0.5 on 2022-07-10 19:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_domain_notifications_alter_user_is_staff'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Notifications',
        ),
    ]
