# Generated by Django 4.1.1 on 2022-09-14 15:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_domain'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
