# Generated by Django 4.0.5 on 2022-07-16 13:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_rename_first_name_user_role_remove_user_is_manager_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='user',
            table='api_user',
        ),
    ]
