# Generated by Django 4.0.5 on 2022-07-19 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_user_table'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='invitation_link',
        ),
        migrations.AlterField(
            model_name='domain',
            name='company_email',
            field=models.EmailField(max_length=100, unique=True),
        ),
    ]
