# Generated by Django 4.1.1 on 2022-09-15 18:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_rename_avatar_user_profile_img_remove_user_bio_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
