# Generated by Django 4.1.1 on 2022-09-15 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='domain',
            field=models.CharField(max_length=300),
        ),
    ]
