# Generated by Django 4.1.1 on 2022-09-15 18:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_remove_user_last_login'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='user',
            name='last_name',
        ),
    ]
