# Generated by Django 4.0.5 on 2022-08-25 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_invitation'),
    ]

    operations = [
        migrations.AddField(
            model_name='invitation',
            name='workspacename',
            field=models.CharField(default='blank', max_length=250),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='profile_img',
            field=models.ImageField(default='blank-profile-picture.png', upload_to='profile_img'),
        ),
    ]
