# Generated by Django 4.1.1 on 2022-09-15 23:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_remove_user_first_name_remove_user_last_name'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Log',
        ),
    ]
