# Generated by Django 4.0.5 on 2022-08-25 14:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_invitation_workspacename_user_profile_img'),
    ]

    operations = [
        migrations.DeleteModel(
            name='invitation',
        ),
    ]
