# Generated by Django 4.0.5 on 2022-08-25 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_delete_invitation'),
    ]

    operations = [
        migrations.CreateModel(
            name='invitation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=50)),
                ('invitation_link', models.CharField(max_length=250, unique=True)),
                ('workspacename', models.CharField(max_length=250)),
            ],
        ),
    ]
