# Generated by Django 4.0.5 on 2022-08-26 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_invitation'),
    ]

    operations = [
        migrations.AddField(
            model_name='domain',
            name='pas_reset',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='domain',
            name='verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='pas_reset',
            field=models.BooleanField(default=False),
        ),
    ]
