# Generated by Django 4.1.1 on 2022-10-05 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_alter_user_profile_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_img',
            field=models.ImageField(default='https://res.cloudinary.com/dg4zlcau8/image/upload/v1664952781/media/profile_img/cli_pcewh0.png', upload_to='profile_img'),
        ),
    ]
