# Generated by Django 4.1.1 on 2022-09-15 23:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_alter_publicchatroom_users'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='publicroomchatmessage',
            name='room',
        ),
        migrations.RemoveField(
            model_name='publicroomchatmessage',
            name='user',
        ),
        migrations.DeleteModel(
            name='PublicChatRoom',
        ),
        migrations.DeleteModel(
            name='PublicRoomChatMessage',
        ),
    ]
